### ISSUE TITLE
Meta: update/upgrade package management

### ISSUE THREAD

**Issue by kangarang** [hop-protocol/hop#162]
currently we git-ignore package lock files and rely on each individual machine to correctly install dependencies for each individual (lerna) package. we should use lock files to keep our `node_modules` synced across local and remote environments. additionally, i propose we adopt yarn package manager throughout the monorepo -- installations are quicker, error messages are clearer, and the cli is cleaner (imo).

steps to update/upgrade package management:
- [x] rm `package-lock.json` and `yarn.lock` from `.gitignore` (and local workspace if present)
- [x] simplify nested `.gitgnore` files (rm extraneous lines)
- [x] update/set node/yarn versions: add `engines.node: "^12.22.1"`/`engines.yarn: "^1.22.11"` to `package.json`
- [ ] (optional) allow minor package diffs using `^` (e.g. `"react": "^17.0.2",`)
- [x] upgrade dependencies (run `yarn install`, which creates `yarn.lock`)

for completeness, replace instances where we use the command `npm` -> `yarn` in the following:
- [x] npm scripts (`package.json`)
- [x] readme instructions
- [x] docs

**Comment by miguelmota** [comment]
This all sounds great @kangarang!

Does it make sense to not check in package-lock.json if we use yarn and yarn.lock? Thinking of ways that we can minimize confusion on which package installer to use

**Comment by kangarang** [comment]
@miguelmota yep, we should delete all instances of `package-lock.json` and avoid using it from now on. removing it from `.gitignore` will ensure that none of our environments have it. if we forget to use yarn and it gets created by npm, it'll be obvious during code review
